### ISSUE TITLE
hi.

### ISSUE THREAD

**Issue by aliad0101** [CultureHQ/add-to-calendar#397]

**Comment by aliad0101** [comment]
i means i want to ommit yahoo from the list

**Comment by bsinoimeri** [comment]
Did you find a solution for this question?

**Comment by Avasam** [comment]
@aliad0101 
@bsinoimeri 
Import [makeUrls](https://github.com/CultureHQ/add-to-calendar/blob/master/src/makeUrls.ts) (`import makeUrls from '@culturehq/add-to-calendar/dist/makeUrls'`) and make your own dropdown. Or you can just hide the last option with some CSS :
```css
.chq-atc--dropdown > a:last-of-type {
  display:none;
}
```
